const COLOR_WHITE = '#FFFFFF'
const COLOR_GREEN = '#00EFB2'
const COLOR_DARK = '#010234'
const GRADIANT = 'linear-gradient(90deg, #c127b9 0%, #ff316d 100%)'

const COLOR_IDENTITY = COLOR_GREEN

const COLOR_BUTTON = GRADIANT

const TEXT_PRIMARY = COLOR_WHITE
const TEXT_SECONDARY = COLOR_IDENTITY
const TEXT_OVERLAY = COLOR_DARK

export default {
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TEXT_OVERLAY,
  COLOR_IDENTITY,
  COLOR_BUTTON,
}
