const PAGE_WRAP = 1298
const MAIN_CONTENT_MAX_WIDTH = 1050
const HEADER_FULL_HEIGHT = 80
const HEADER_FOLDED_HEIGHT = 50
const MARGINS = [8, 12, 16, 20, 26]
export default {
  PAGE_WRAP,
  HEADER_FULL_HEIGHT,
  HEADER_FOLDED_HEIGHT,
  MARGINS,
  MAIN_CONTENT_MAX_WIDTH,
}
